/** Chart and legend CSS custom properties used for color inlining during SVG export. */
export const CHART_CSS_VAR_NAMES = [
  "--chart-1",
  "--chart-2",
  "--chart-3",
  "--chart-4",
  "--chart-5",
  "--chart-background",
  "--chart-foreground",
  "--chart-foreground-muted",
  "--chart-line-primary",
  "--chart-line-secondary",
  "--chart-crosshair",
  "--chart-grid",
  "--chart-tooltip-background",
  "--chart-tooltip-foreground",
  "--chart-tooltip-muted",
  "--chart-indicator-color",
  "--chart-indicator-secondary-color",
  "--chart-marker-background",
  "--chart-marker-border",
  "--chart-marker-foreground",
  "--chart-marker-badge-background",
  "--chart-marker-badge-foreground",
  "--chart-segment-background",
  "--chart-segment-line",
  "--chart-ring-background",
  "--chart-label",
  "--legend",
  "--legend-foreground",
  "--legend-muted",
  "--legend-muted-foreground",
  "--legend-track",
] as const;
